### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by seidel1978** [davesc63/fuel-spoof#2]
Congratulations on getting this working with iOS 17. I've got an iPhone SE 2020 on iOS 17.2.1 and the location can be set easily using the script.

Would you be able to add an option to the script to allow setting the location via longitude and latitude?

Thanks so much for making this tool public, it's a great help to get cheap petrol.

**Comment by davesc63** [comment]
Yep that would be an easy option to add!
The challenge is then relying on the end user to obtain those coordinates.

I will update the script for the option, but stay tuned, I am about to release a web app that will do all of this in a much more user friendly way

**Comment by seidel1978** [comment]
Wow, that's fantastic! Are you thinking of having an interactive map to be able to choose coordinates? I'm looking forward to the release.

**Comment by davesc63** [comment]
Feature added, also check out https://geoport.me
