### ISSUE TITLE
Uh oh - No longer works for me

### ISSUE THREAD

**Issue by thcnunz** [davesc63/fuel-spoof#5]
I think an app update (My 7 Eleven 2.18.5) has been released to prevent this from working. Locking in fuel once location is spoofed no longer works and the App throws the error message

 “Uh-oh! That didn’t quite work as planned, there seems to be a problem. Error A01”

Can anyone else confirm ?
Device details:
iOS 17.2.1
iPhone 15 Pro Max

**Comment by davesc63** [comment]
More details please?What no longer works? What app is updated? What iOS?On 7 Feb 2024, at 6:42 pm, thcnunz ***@***.***> wrote:﻿
I think an app update has been released to prevent this from working. Can anyone else confirm ?

**Comment by thcnunz** [comment]
For whatever reason, it wouldn't work whilst the cable was plugged in. (I tried many times). I unplugged the cable and tried again and it worked.
